name: kafka4s
baseurl: /kafka4s
description: Functional programming with Kafka and Scala
highlighter: rouge
docs: true
collections:
  tut:
    output: true
version: 3.0.0-M23+10-8ed98d13-SNAPSHOT
org: Jack Henry & Associates, Inc.Â®
markdown: kramdown
